
services:
  ispn1:
    image: quay.io/infinispan/server:15.0
    container_name: ispn1
    environment:
      USER: admin
      PASS: admin123
      INFINISPAN_NODE_NAME: ispn1
      JGROUPS_TRANSPORT_STACK: tcp
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: initial_hosts=ispn1[7800],ispn2[7800];port_range=0
      # 每个节点独立的数据目录（解决全局锁冲突的关键）
      JAVA_OPTIONS: >-
        -Djboss.server.data.dir=/opt/infinispan/server/data-node1
        -Dinfinispan.cluster.name=ispn-cluster
    ports:
      - "11222:11222"
      - "7800:7800"
    volumes:
      - ispn1_data:/opt/infinispan/server/data-node1

  ispn2:
    image: quay.io/infinispan/server:15.0
    container_name: ispn2
    environment:
      USER: admin
      PASS: admin123
      INFINISPAN_NODE_NAME: ispn2
      JGROUPS_TRANSPORT_STACK: tcp
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: initial_hosts=ispn1[7800],ispn2[7800];port_range=0
      JAVA_OPTIONS: >-
        -Djboss.server.data.dir=/opt/infinispan/server/data-node2
        -Dinfinispan.cluster.name=ispn-cluster
    ports:
      - "11223:11222"
      - "7801:7800"
    volumes:
      - ispn2_data:/opt/infinispan/server/data-node2

volumes:
  ispn1_data:
  ispn2_data:
